name: meta-macchina-docker-ci
on: [push]
jobs:
  docker-build-x86_64:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker Image
        run: docker build . -t macchina/edge-ce
      -
        name: Push Docker Image
        run: docker push macchina/edge-ce

  docker-build-armv7:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --tag macchina/edge-ce:latest \
            --file ./Dockerfile .

  docker-build-armv64:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=true" \
            --tag macchina/edge-ce:latest \
            --file ./Dockerfile .
