name: meta-macchina-docker-ci
on: [push]
jobs:
  docker-build-x86_64:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Docker Image
        run: docker build . -t macchina/edge-ce

  docker-build-arm:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build Docker Image
        run: |
          docker buildx build \
            --platform linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --file ./Dockerfile .
